
[font]

# normal.family = "Cascadia Code NF"
# normal.family = "Maple Mono"
normal.family = "VictorMono Nerd Font"
normal.style = "Medium"
# normal.family = "JetBrainsMono Nerd Font"
size = 13.0
offset.x = 1
# offset.y = 4

[keyboard]

bindings = [
  { key = "6", mods = "Control", chars = "\u001e" }
]

[env]
term = "xterm-255color"

[window]
option_as_alt = 'Both'

[general]
# https://github.com/alacritty/alacritty-theme
import = [
  # "~/.config/alacritty/themes/themes/solarized_osaka.toml"
  # "~/.config/alacritty/themes/themes/rose-pine.toml"
  "~/.config/alacritty/themes/themes/nordic.toml",
]
